### ISSUE TITLE
New feature request in cito

### ISSUE THREAD

**Issue by ghuter** [terminalforlife/Extra#2]
Hi
this is not really an issue but just something I would really appreciate to see in the 'cito' script:
I would like to be able to install a remote program without always having to use root rights, especially when I'm going to install it in $HOME/.local/bin for example (-T option)
As I'm new to shell programming and this could eventually benefit other people, I prefer to tell you about it directly
thank you in advance

**Comment by terminalforlife** [comment]
Hi, this is something I'd like as well, because I often need to 'install' my BashConfig, i3Config, and VimConfig repositories on other machines.

However, the root privileges aren't just for show; they allow fairly strict logging into `/var/log/cito-events.log`. That being said, I could certainly add in an option to disable logging and therefore the _need_ for root privileges.

I'll look into it, and this is good idea for an issue; even added a tag for just this purpose. :)

**Comment by terminalforlife** [comment]
There you go. Install the latest version with Cito:

```
sudo cito -r terminalforlife Extra master source/cito
```

Please let me know if there are any issues or if you have anything else you'd like to see, in Cito or otherwise.

**Comment by ghuter** [comment]
Okay, it's working fine for me. Thank you!
